name: Bug Report
description: Report a bug or unexpected behavior.

body:
  - type: textarea
    id: explanation

    attributes:
      label: Explanation
      description: |
        Clearly describe the bug.
        Include what you were trying to do and what went wrong.

    validations:
      required: true

  - type: checkboxes
    id: bug_type

    attributes:
      label: Bug Type
      description: Select all that apply.
      options:
        - label: Runtime error
        - label: Security issue
        - label: Performance issue
        - label: Incorrect behavior
        - label: Documentation issue
        - label: Other

  - type: textarea
    id: reproduction

    attributes:
      label: Steps to Reproduce
      description: |
        Provide clear steps so we can reproduce the issue.

        Example:
        1. Install the package
        2. Configure authentication with X
        3. Call endpoint Y
        4. See error Z

    validations:
      required: true

  - type: textarea
    id: expected_behavior

    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

    validations:
      required: true

  - type: textarea
    id: actual_behavior

    attributes:
      label: Actual Behavior
      description: What actually happened?

    validations:
      required: true

  - type: textarea
    id: environment

    attributes:
      label: Environment
      description: |
        Please provide the following details:
        - OS:
        - Python version:
        - Django version:
        - Django REST Framework version:
        - Package version / commit hash:

    validations:
      required: false

  - type: textarea
    id: additional_context

    attributes:
      label: Additional Context
      description: |
        Add any other context, logs, stack traces, or screenshots here.

    validations:
      required: false
